# Cloudflare Pages — Functions + KV 同步
name = "cl-nav"
compatibility_date = "2024-11-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "CL_NAV_SYNC"
id = "fbfee28c0c54443fb8d4aabc9b68880b"
